# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    carthage(platform: "iOS,Mac", cache_builds: true)
  end

  desc "Description of what the lane does"
  lane :test do
    Dir.chdir '..' do
      sh("rake test:ios")
      sh("rake test:osx")
    end
  end
end
